function valuap(respuest){ //recibe un entero que indica la respuesta seleccionada
	var reto;
	if(parseInt(respuest)==this.correcta){
		// var reto;
		alert("Es correcta");
		reto=true;
		return reto;
	}else{
		alert("Es false");
		return reto;
	}
}

function pregunta(pregun,respuesta1,respuesta2,respuesta3,respuesta4,correcta){
	this.pregun=pregun;
	this.respuestas=[];
	this.respuestas[0]=respuesta1;
	this.respuestas[1]=respuesta2;
	this.respuestas[2]=respuesta3;
	this.respuestas[3]=respuesta4;
	this.correcta=parseInt(correcta);
	this.ocupado=false;
	this.valuap=valuap;
}

var retorno=[];
var preguntas=[];


preguntas[0]=new pregunta("¿Qué es el diseño arquitectónico?","Proceso multiface en el que se sintetiza representaciones de la estructura de datos","Proceso multiface en el que se sintetiza la estructura del programa","Proceso multiface en el que se sintetiza las características de la interfaz y los detalles procedimentales desde los requisitos de la información", "Todas las Anteriores",3);
preguntas[1]=new pregunta("¿Cuál es el producto obtenido?","Se crea un modelo de arquitectura que abarca la arquitectura de datos y la estructura del programa","Proceso multiface en el que se sintetiza representaciones de la estructura de datos","Un sistema de programa o computación","El software operacional",0);
preguntas[2]=new pregunta("¿Qué es la arquitectura?","El software operacional","Es la estructura de las estructuras del sistema","Alternativas arquitectónicas en una etapa en la cual hacer cambios en el diseño es relativamente fácil","Modelo de arquitectura que abarca la arquitectura de datos y la estructura del programa",1);
preguntas[3]=new pregunta("¿Cuál es la representación que capacita al ingeniero del software para analizar la efectividad del diseño?"," Alternativas ","Las representaciones de la arquitectura ","La arquitectura","Diseño",2);
preguntas[4]=new pregunta("¿Cuál es alguna de las importancias de la arquitectura del software?","Las representaciones de la arquitectura de software facilitan la comunicación entre todas las partes interesadas en el desarrollo de un sistema basado en computadoras","La arquitectura destaca decisiones tempranas de diseño que tendrán un profundo impacto en todo el trabajo de ingeniería del software que sigue, y es tan importante en el éxito final del sistema como una entidad operacional","La arquitectura constituye el modelo relativamente pequeño e intelectual comprensible de cómo está estructurado el sistema y de cómo trabajan juntos sus componentes","Todas las anteriores",3);
preguntas[5]=new pregunta("¿Cuál es alguno de los aspectos del diseño arquitectónico?","Planeación y Diseño ","Seguridad","Enfoque","Todo lo anterior",3);
preguntas[6]=new pregunta("¿Cuáles son algunos de los pasos de la transformación?","Derivación de una o más representaciones de la estructura arquitectónica del sistema","Ninguna de las anteriores","El diseño de datos","a y c",3);
preguntas[7]=new pregunta("¿En qué consiste la complejidad arquitectónica?"," Técnica útil consiste en considerar las relaciones de dependencia entre los componentes de la arquitectura "," Relaciones de dependencia ","Estructura arquitectónica del sistema","b y c",0);
preguntas[8]=new pregunta("¿Qué es el  diseño de datos?"," Impacto de la estructura de datos sobre la estructura del programa","a y c","Parte esencial en la creación de aplicaciones de alta calidad","Ninguna de las anteriores",2);
preguntas[9]=new pregunta("¿En qué consiste la arquitectura de flujo de datos?","Esta estructura clásica de programación descompone las funciones en una jerarquía de control donde un programa llama un número de componentes de programa los cuales en respuesta pueden llamar a otros componentes","Esta arquitectura se aplica cuando los datos de entrada son transformados a través de una serie de componentes computacionales o manipulativos en los datos de salida","Se crean diferentes capas y cada una realiza operaciones que progresivamente se aproximan más al cuadro de instrucciones de la máquina ","Permite al diseñador del software construir una estructura de programa relativamente fácil de modificar y ajustar a escala ",1);
preguntas[10]=new pregunta("¿En qué consiste la arquitectura de llamadas de retorno?","Esta estructura clásica de programación descompone las funciones en una jerarquía de control donde un programa llama un número de componentes de programa los cuales en respuesta pueden llamar a otros componentes","Esta arquitectura se aplica cuando los datos de entrada son transformados a través de una serie de componentes computacionales o manipulativos en los datos de salida","Se crean diferentes capas y cada una realiza operaciones que progresivamente se aproximan más al cuadro de instrucciones de la máquina ","Permite al diseñador del software construir una estructura de programa relativamente fácil de modificar y ajustar a escala ",3);
preguntas[11]=new pregunta("¿En qué consiste la arquitectura estratificada?","Esta estructura clásica de programación descompone las funciones en una jerarquía de control donde un programa llama un número de componentes de programa los cuales en respuesta pueden llamar a otros componentes","Esta arquitectura se aplica cuando los datos de entrada son transformados a través de una serie de componentes computacionales o manipulativos en los datos de salida","Se crean diferentes capas y cada una realiza operaciones que progresivamente se aproximan más al cuadro de instrucciones de la máquina ","Permite al diseñador del software construir una estructura de programa relativamente fácil de modificar y ajustar a escala ",2);
preguntas[12]=new pregunta("¿En qué consiste la arquitectura de programa principal subprograma?","Esta estructura clásica de programación descompone las funciones en una jerarquía de control donde un programa llama un número de componentes de programa los cuales en respuesta pueden llamar a otros componentes","Esta arquitectura se aplica cuando los datos de entrada son transformados a través de una serie de componentes computacionales o manipulativos en los datos de salida","Se crean diferentes capas y cada una realiza operaciones que progresivamente se aproximan más al cuadro de instrucciones de la máquina ","Permite al diseñador del software construir una estructura de programa relativamente fácil de modificar y ajustar a escala ",0);
preguntas[13]=new pregunta("¿En qué consiste la arquitectura orientada a objetos?","Los componentes de un sistema encapsulan los datos y las operaciones que se deben realizar para manipular los datos","Ninguna de las opciones" ,"La comunicación y la coordinación entre componentes se consiguen a través del paso de mensajes","Los componentes de una arquitectura están distribuidos entre varias computadoras en una red",3);
preguntas[14]=new pregunta("Menciona algún modelo:","Modelo de nivelación","Modelo de  capas","Modelo cliente servidor","Todas las anteriores",3);
preguntas[15]=new pregunta("En el flujo de transformación-----","La información entra en el sistema a lo largo de caminos que transforman los datos externos a un formato interno ","El modelo fundamental del sistema comprende el DFD de nivel 0 y la información que lo soporta ","a y d","Se identifican como flujo de entradas",2);
preguntas[16]=new pregunta("¿En qué consiste el paso 1 de la transformación?","Revisar y refinar los diagramas de flujo de datos del software","Determinar si el DFD tiene características de flujo de transformación o de transacción","Revisar el modelo fundamental del sistema","Aislar el centro de transformación especificando los límites de los flujos de entrada y salida",2);
preguntas[17]=new pregunta("¿En qué consiste el paso 2 de la transformación?","Revisar y refinar los diagramas de flujo de datos del software","Determinar si el DFD tiene características de flujo de transformación o de transacción","Revisar el modelo fundamental del sistema","Aislar el centro de transformación especificando los límites de los flujos de entrada y salida",0);
preguntas[18]=new pregunta("¿En qué consiste el paso 3 de la transformación?","Revisar y refinar los diagramas de flujo de datos del software","Determinar si el DFD tiene características de flujo de transformación o de transacción","Revisar el modelo fundamental del sistema","Aislar el centro de transformación especificando los límites de los flujos de entrada y salida",1);
preguntas[19]=new pregunta("¿En qué consiste el paso 4 de la transformación?","Revisar y refinar los diagramas de flujo de datos del software","Determinar si el DFD tiene características de flujo de transformación o de transacción","Revisar el modelo fundamental del sistema","Aislar el centro de transformación especificando los límites de los flujos de entrada y salida",3);
preguntas[20]=new pregunta("¿En qué consiste el paso 5 de la transformación?","Revisar y refinar los diagramas de flujo de datos del software","Realizar una descomposición de primer nivel","Revisar el modelo fundamental del sistema","Aislar el centro de transformación especificando los límites de los flujos de entrada y salida",1);
preguntas[21]=new pregunta("¿En qué consiste el paso 6 de la transformación?","Revisar y refinar los diagramas de flujo de datos del software","Realizar una descomposición de primer nivel","Revisar el modelo fundamental del sistema","Realizar descomposición de segundo nivel",3);
preguntas[22]=new pregunta("¿En qué consiste el paso 7 de la transformación?","Revisar y refinar los diagramas de flujo de datos del software","Realizar una descomposición de primer nivel","Refinar la estructura inicial de la arquitectura usando heurística para mejorar la calidad del software","Realizar descomposición de segundo nivel",2);
preguntas[23]=new pregunta("¿En qué consiste el paso 1 de la transacción?","Revisar y refinar los diagramas de flujo de datos del software","Determinar si el DFD tiene características de flujo de transformación o de transacción","Revisar el modelo fundamental del sistema","Aislar el centro de transformación especificando los límites de los flujos de entrada y salida",2);
preguntas[24]=new pregunta("¿En qué consiste el paso 2 de la transacción?","Revisar y refinar los diagramas de flujo de datos del software","Determinar si el DFD tiene características de flujo de transformación o de transacción","Revisar el modelo fundamental del sistema","Aislar el centro de transformación especificando los límites de los flujos de entrada y salida",0);
preguntas[25]=new pregunta("¿En qué consiste el paso 3 de la transacción?","Revisar y refinar los diagramas de flujo de datos del software","Determinar si el DFD tiene características de flujo de transformación o de transacción","Revisar el modelo fundamental del sistema","Aislar el centro de transformación especificando los límites de los flujos de entrada y salida",1);
preguntas[26]=new pregunta("¿En qué consiste el paso 4 de la transacción?","Revisar y refinar los diagramas de flujo de datos del software","Identificar el centro de transacción y las características de flujo a lo largo de cada camino de acción","Refinar la estructura inicial de la arquitectura usando heurística para mejorar la calidad del software","Realizar descomposición de segundo nivel",1);
preguntas[27]=new pregunta("¿En qué consiste el paso 5 de la transacción?","Revisar y refinar los diagramas de flujo de datos del software","Identificar el centro de transacción y las características de flujo a lo largo de cada camino de acción","Refinar la estructura inicial de la arquitectura usando heurística para mejorar la calidad del software","Transformar el DFD en una estructura de programa adecuada al procesamiento de la transacción",3);

